[package]
name = "cargo-rm"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Remove Cargo.lock lockfile"
repository = "https://github.com/dtolnay/cargo-rm"
documentation = "https://github.com/dtolnay/cargo-rm"
keywords = ["cargo", "subcommand"]
categories = ["development-tools::cargo-plugins"]
edition = "2018"
readme = "README.md"

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
